/* ================================================================== *
 *  Written by Jason Merlo
 *
 *  File: muse.cpp
 *
 *  Description: Defines visualizer webpage content
 * ================================================================== */

#ifndef WEBPAGE_CONSTANTS_H
#define WEBPAGE_CONSTANTS_H

static const unsigned char control_panel[] = "<!DOCTYPE html>"
"<html>"
    "<head>"
        "<title>MUSE Control Panel</title>"
        "<style>"
            "body {"
                "background-color: #002058;"
                "font-family: sans-serif;"
                "text-align: center;"
            "}"
            "h1 {"
                "color: #E87722;"
                "text-align: center;"
            "}"
            "div {"
                "display: inline-block;"
                "width: 60%;"
            "}"
            "form {"
                "color: #E87722;"
                "font-size: 24px;"
                "text-align: left;"
            "}"
            "input[type=radio] {"
                "-webkit-appearance: button;"
                "-moz-appearance: button;"
                "-o-appearance: button;"
                "-ms-appearance: button;"
                "appearance: button;"
            "}"
            "label:hover {"
                "background:#606EB2;"
            "}"
        "</style>"
        "<script>"
            "function handleClick(myRadio) {"
                "switch (myRadio) {"
                    "case 0:"
                        "document.getElementById('visualizer_form').submit();"
                        "break;"
                    "case 1:"
                        "document.getElementById('other_form').submit();"
                        "break;"
                    "case 2:"
                        "document.getElementById('power_form').submit();"
                        "break;"
                    "default: break;"
                "}"
            "}"
        "</script>"
        "<meta id='meta' name='viewport' content='height=device-height; initial-scale=1.0' />"
    "</head>"
    "<body>"
        "<div id='visualizer_div'>"
            "<h1>Visualizers</h1>"
            "<form id='visualizer_form' action='/web_input' method='post'>"
                "<label for='v1'><input type='radio' id='v1' name='visualizer' onclick='handleClick(0)' value='0'></input>Bars</label><br>"
                "<label for='v2'><input type='radio' id='v2' name='visualizer' onclick='handleClick(0)' value='1'></input>Bars Middle</label><br>"
                "<label for='v3'><input type='radio' id='v3' name='visualizer' onclick='handleClick(0)' value='2'></input>Plasma</label><br>"
                "<label for='v4'><input type='radio' id='v4' name='visualizer' onclick='handleClick(0)' value='3'></input>Pulse</label><br>"
                "<label for='v5'><input type='radio' id='v5' name='visualizer' onclick='handleClick(0)' value='4'></input>Rainbow</label><br>"
                "<label for='v6'><input type='radio' id='v6' name='visualizer' onclick='handleClick(0)' value='5'></input>Wheel</label><br>"
            "</form>"
        "</div>"
        "<br><br>"
        "<div id='other_div'>"
            "<h1>Others</h1>"
            "<form id='other_form' action='/web_input' method='post'>"
                "<label for='o1'><input type='radio' id='o1' name='other' onclick='handleClick(1)' value='66'></input>Ambient Light</label><br>"
                "<label for='o2'><input type='radio' id='o2' name='other' onclick='handleClick(1)' value='77'></input>Bouncing Lines</label><br>"
                "<label for='o3'><input type='radio' id='o3' name='other' onclick='handleClick(1)' value='88'></input>Bar Test</label><br>"
                "<label for='o4'><input type='radio' id='o4' name='other' onclick='handleClick(1)' value='99'></input>Pixel Test</label><br>"
            "</form>"
        "</div>"
        "<div id='power_div'>"
            "<h1>Power</h1>"
            "<form id='power_form' action='/web_input' method='post'>"
                "<label for='p1'><input type='radio' id='p1' name='power' onclick='handleClick(2)' value='1'></input>Power On</label><br>"
                "<label for='p2'><input type='radio' id='p2' name='power' onclick='handleClick(2)' value='0'></input>Power Off</label><br>"
            "</form>"
        "</div>"
    "</body>"
"</html>";

#endif
