/* ================================================================== *
 *  Written by Jason Merlo
 *
 *  File: muse.cpp
 *
 *  Description: Defines visualizer webpage content
 * ================================================================== */

#ifndef WEBPAGE_CONSTANTS_H
#define WEBPAGE_CONSTANTS_H

static const unsigned char control_panel[] = "<!DOCTYPE html>"
"<html>"
    "<head>"
        "<title>MUSE Control Panel</title>"
        "<link href='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css' rel=stylesheet />"
        "<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js'></script>"
        "<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js'></script>"
        "<style>"
            "body {"
                "background-color: #002058;"
                "font-family: sans-serif;"
                "text-align: center;"
            "}"
            "h1 {"
                "color: #E87722;"
                "text-align: center;"
            "}"
            "div {"
                "display: inline-block;"
                "width: 60%;"
            "}"
            "button {"
                "background-color: #002058;"
                "border-color: #002058;"
                "color: #E87722;"
                "font-size: 24px;"
                "text-align: left;"
            "}"
            "button:hover {"
                "background-color: #606EB2;"
                "border-color: #606EB2;"
            "}"
        "</style>"
        "<meta id='meta' name='viewport' content='height=device-height, initial-scale=1.0' />"
        "<script>"
            "$(document).ready(function() {"
                "$('#visualizer_div>button').click(function(event){"
                    "$.post('/web_input', {visualizer: event.target.value});"
                "}),"
                "$('#other_div>button').click(function(event){"
                    "$.post('/web_input', {other: event.target.value});"
                "}),"
                "$('#power_div>button').click(function(event){"
                    "$.post('/web_input', {power: event.target.value});"
                "})"
            "});"
        "</script>"
    "</head>"
    "<body>"
        "<div id='visualizer_div'>"
            "<h1>Visualizers</h1>"
            "<button value='0'>Bars</button>"
            "<button value='1'>Bars Middle</button>"
            "<button value='2'>Plasma</button>"
            "<button value='3'>Pulse</button>"
            "<button value='4'>Rainbow</button>"
            "<button value='5'>Wheel</button>"
        "</div>"
        "<br><br>"
        "<div id='other_div'>"
            "<h1>Others</h1>"
            "<button value='66'>Ambient Light</button>"
            "<button value='77'>Bouncing Lines</button>"
            "<button value='88'>Bar Test</button>"
            "<button value='99'>Pixel Test</button>"
        "</div>"
        "<br><br>"
        "<div id='power_div'>"
            "<h1>Power</h1>"
            "<button value='1'>Power On</button>"
            "<button value='0'>Power Off</button>"
        "</div>"
    "</body>"
"</html>";

#endif
